### ISSUE TITLE
Bug. UI. /providers endpoint is called twice on first load

### ISSUE THREAD

**Issue by podkolzzzin** [podkolzzzin/QueryPressure#21]
# Steps to reproduce:
Load the main page of application and view Chrome Dev Tools/Network tab
# Expected result:
/providers is called once
# Actual result:
/provider is called twice

![image](https://user-images.githubusercontent.com/1740940/225966606-12618e85-3ca9-4520-956d-9074a5b5c0f5.png)

**Comment by TheHACKATHON** [comment]
Its not a bug. This will only happen in dev mode. 
This happens because we use React.StrictMode, it runs some hooks twice at a time to find potential bugs. 

Read more here https://legacy.reactjs.org/docs/strict-mode.html

**Comment by podkolzzzin** [comment]
Ooo! Really interesting!)

> Its not a bug. This will only happen in dev mode. This happens because we use React.StrictMode, it runs some hooks twice at a time to find potential bugs.
> 
> Read more here https://legacy.reactjs.org/docs/strict-mode.html
