### ISSUE TITLE
Bug. Single-threaded sequential profile with query count limit deadlocked at the end of execution 

### ISSUE THREAD

**Issue by demchenkov** [podkolzzzin/QueryPressure#53]
#### The `Single-threaded sequential` profile with `query count` limit is deadlocked at the end of execution or after cancelation 
---
It works fine, load testing was done but at the last iteration looks like the execution task is deadlocked
Task stays in the status `WaitingForActivation`. Task cancellation also doesn't help. 
It leads to a few issues: Memory leaks, front-end artifacts, etc.

**Comment by podkolzzzin** [comment]
Yep..
There was a problem.
I have fixed it using TaskCompletionSourceWithCancellation after merging your PR.
Thank you for submitting issue
